force-app/main/default/objects/Case/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <label>WTG</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WTG</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Installation_date__c.field-meta.xml
<CustomField>
    <fullName>Installation_date__c</fullName>
    <label>Installation date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases (Order)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Montréal and Gatineau Regions</fullName>
            </value>
            <value>
                <fullName>Quebec Region</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sage_ID__c.field-meta.xml
<CustomField>
    <fullName>Sage_ID__c</fullName>
    <formula>Account.Sage_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sage ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contractor_Invoice_Settings__c/Contractor_Invoice_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Contractor Invoice Settings</label>
</CustomObject>

force-app/main/default/objects/Contractor_Invoice_Settings__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drawer for Orders</relationshipLabel>
    <relationshipName>Drawing_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Actual_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Delivery_Date__c</fullName>
    <label>Actual Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contract_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <description>Picklist used to match objects records with Work Type Groups</description>
    <label>WTG</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WTG</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Designer__c.field-meta.xml
<CustomField>
    <fullName>Designer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Designer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Designer)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Utilisé pour l&apos;intégration des sondages</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order/fields/Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Family_Name__c</fullName>
    <description>Utilisé pour l&apos;intégration des sondages</description>
    <label>Family Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Financing_Amount__c.field-meta.xml
<CustomField>
    <fullName>Financing_Amount__c</fullName>
    <label>Financing Amount</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Utilisé pour l&apos;intégration des sondages</description>
    <label>First Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Installation_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Date__c</fullName>
    <label>Installation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>Sage Order Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Pick_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Pick_Up_Date__c</fullName>
    <label>Pick-Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>IF(ISPICKVAL($User.LanguageLocaleKey, &apos;fr&apos;), 
    TEXT(Address__r.Region__c), 
    CASE(  Address__r.Region__c  , 
        &apos;Montréal&apos;, &apos;Montreal&apos;, 
        &apos;Québec&apos;, &apos;Quebec&apos;,
        &apos;Nouveau-Brunswick&apos;,&apos;New Brunswick&apos;, 
        TEXT(Address__r.Region__c))   )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sage_ID__c.field-meta.xml
<CustomField>
    <fullName>Sage_ID__c</fullName>
    <externalId>true</externalId>
    <label>Sage ID</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Salesperson_1__c.field-meta.xml
<CustomField>
    <fullName>Salesperson_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson 1</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$User.Salesperson_ID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>This record type is designed to handle orders that are part of a contractual agreement. It includes fields and processes tailored to managing contract-specific details.</description>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Quantity_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Shipped__c</fullName>
    <label>Quantity Shipped</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sage_ID__c.field-meta.xml
<CustomField>
    <fullName>Sage_ID__c</fullName>
    <externalId>true</externalId>
    <label>Sage ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Serial__c.field-meta.xml
<CustomField>
    <fullName>Serial__c</fullName>
    <label>Serial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sage_ID__c.field-meta.xml
<CustomField>
    <fullName>Sage_ID__c</fullName>
    <externalId>true</externalId>
    <label>Sage ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <formula>TEXT(Product2.Contract_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CR</fullName>
                <label>In ground Pool</label>
            </value>
            <value>
                <fullName>SC</fullName>
                <label>Semi in ground Pool</label>
            </value>
            <value>
                <fullName>HT</fullName>
                <label>Off ground Pool</label>
            </value>
            <value>
                <fullName>Spa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sage_ID__c.field-meta.xml
<CustomField>
    <fullName>Sage_ID__c</fullName>
    <externalId>true</externalId>
    <label>Sage ID</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkType/fields/Capacity_Type__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Type__c</fullName>
    <label>Capacity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Work_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkType/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Work Types</relationshipLabel>
    <relationshipName>Work_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkType/fields/Sage_ID__c.field-meta.xml
<CustomField>
    <fullName>Sage_ID__c</fullName>
    <externalId>true</externalId>
    <label>Sage ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Generic/TestDataFactory.cls
public class TestDataFactory {
    public static Account createTestAccount() {
        return new Account(
            Name = 'Test Account',
            BillingStreet = '123 Street',
            BillingCity = 'Ottawa',
            BillingState = 'Ontario',
            BillingPostalCode = 'K1K1K1',
            BillingCountryCode = 'CA',
            Sage_ID__c = 'SAGE123',
            Email__c = 'test@example.com',
            Cellphone__c = '5555555555',
            Phone = '5551234567'
        );
    }
    public static Contact createTestContact(Id accountId) {
        return new Contact(
            firstName = 'firstName',
            lastName = 'Test Contact',
            AccountId = accountId,
            MobilePhone = '1133443322',
            Email = 'test@example.co'
            );
    }

    
    public static User createTestUser(String firstName,String lastName,Id roleId) {
        return new User(
                Alias = 'tadmin',
                Email = 'hellohella@toto.com',
                EmailEncodingKey = 'UTF-8',
                FirstName = firstName,
                LastName = lastName,
                isActive = true,
                UserRoleId = roleId,
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id,
                TimeZoneSidKey = 'America/New_York',
                Username = 'hellohella@toto.com'
        );
    }
    public static UserRole createTestUserRole() {
        return new UserRole(
                Name = 'devops'
        );
    }

    public static Product2 createTestProduct(String name, String productCode) {
        return new Product2(
            Name = name,
            Sage_ID__c = productCode,
            IsActive = true
        );
    }

    public static Order createTestOrder(Id accountId, Id pricebookId, String contractNumber) {
        return new Order(
            AccountId = accountId,
            EffectiveDate = Date.today(),
            Status = 'Analysis',
            Pricebook2Id = pricebookId,
            ShippingCountryCode = 'CA', 
            ShippingStateCode = 'ON',
            Order_Number__c = contractNumber
        );
    }
    public static Order createTestOrderForDelivery(Id accountId,Id userId) {
        return new Order(

        AccountId = accountId,
        RecordTypeId = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('Contract').getRecordTypeId(),
        Status = 'Completed',
        EffectiveDate = Date.today(),
        ShippingCountryCode = 'CA', 
        ShippingStateCode = 'ON',
        Pricebook2Id = Test.getStandardPricebookId(),
        Order_Number__c = 'TEST-ORDER-123',
        Location__c = null,
        Contract_Type__c = '115',
        Pick_Up_Date__c = Date.today().addYears(-1),
        Actual_Delivery_Date__c = Date.today().addYears(-1),
        Installation_Date__c = null,
        Financing_Amount__c = 1000,
        Designer__c = accountId,
        Salesperson_1__c = userId,
        Order_Total__c = 5000,
        Family_Name__c = 'Test Family',
        First_Name__c = 'Test First',
        Email__c = 'test@example.com'
        );
    }
 




    public static PricebookEntry createTestPricebookEntry(Id productId, Id pricebookId) {
        return new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = productId,
            UnitPrice = 100,
            IsActive = true
        );
    }

    public static OrderItem createTestOrderItem(Id orderId, Id productId, Id pricebookEntryId) {
        return new OrderItem(
            OrderId = orderId,
            Product2Id = productId,
            Serial__c = '43',
            Quantity = 1,
            UnitPrice = 100,
            PricebookEntryId = pricebookEntryId
        );
    }

    public static Shipment createTestShipment(Id orderId) {
        return new Shipment(
            Order__c = orderId,
            ShipToName = 'test'
        );
    }

    public static ShipmentItem createTestShipmentItems(Id shipmentId, Id productId) {
        return new ShipmentItem(
            ShipmentId = shipmentId,
            Product2Id = productId,
            Quantity = 2,
            Quantity_Shipped__c = 2
        );
    }

    

    public static Case createTestCase() {
        return new Case(
            Subject = 'Test Case'
        );
    }

    public static Contractor_Invoice_Settings__c createServiceAppointmentSettings() {
        return new Contractor_Invoice_Settings__c(
            Invoice_Number__c = '1000'
        );
    }
 
    public static Pricebook2 createTestPricebook() {
        return new Pricebook2(
            Name = 'Test Pricebook',
            IsActive = true
        );
    }

    public static Resource__c createTestResource(Id pricebookId,Id accountId) {
        return new Resource__c(
            Name = 'Test Resource',
            Tariffication_Method__c = 'Fixed Fees',
            Price_Book__c = pricebookId,
            Account__c = accountId,
            Resource_Level__c = '1'
        );
    }

    public static WorkType createTestWorkType(Id productId) {
        return new WorkType(
            Name = 'Livraison AB',
            EstimatedDuration = 30,
            DurationType = 'Hours',
            Product__c = productId,
            Capacity_Type__c = 'Livraison'

        );
    }

    public static WorkOrder createTestWorkOrder(Id accountId) {
        return new WorkOrder(
            Description = 'Test Work Order',
            AccountId = accountId
        );
    }

    public static OperatingHours createTestOperatingHours() {
        return new OperatingHours(
            Name = 'Test OperatingHours'
        );
    }

    public static ServiceTerritory createTestServiceTerritory(Id OperatingHoursId) {
        return new ServiceTerritory(
            Name = 'Test ServiceTerritory',
            IsActive = true,
            OperatingHoursId = operatingHoursId
        );
    }

    public static WorkOrderLineItem createTestWorkOrderLineItem(Id workOrderId, Id orderId, Id workTypeId, Id productId) {
        return new WorkOrderLineItem(
            Description = 'Test WOLI',
            WorkTypeId = workTypeId,
            OrderId = orderId,
            WorkOrderId = workOrderId,
            Region__c = 'Montreal',
            Product__c = productId,
            ContractType__c =  '45'
           );
    }

    public static ServiceAppointment createTestServiceAppointment(Id woliId,Id serviceTerritoryId,Id serviceResourceId) {
        return new ServiceAppointment(
            ActualStartTime = System.now(),
            ParentRecordId = woliId,
            Description = 'Test Appointment',
            Status = 'Waiting for customer confirmation',
            SchedStartTime = System.now(),
            SchedEndTime = System.now(),
            FSSK__FSK_Assigned_Service_Resource__c = serviceResourceId,
            ServiceTerritoryId = serviceTerritoryId
        );
    }

    
    public static ServiceResource createTestServiceResource(Id accountId, Id userId) {
        return new ServiceResource(
            Name = 'test',
            AccountId = accountId,
            RelatedRecordId = userId,
            isActive = true
        );
    }

    public static AssignedResource createTestAssignedResource(Id serviceResourceId,Id serviceAppointmentId) {
        return new AssignedResource(
            ServiceResourceId = serviceResourceId,
            ServiceAppointmentId = serviceAppointmentId
        );
    }

    public static ServiceTerritoryMember createTestServiceTerritoryMember(Id serviceTerritoryId, Id serviceResourceId,Id operatingHoursId) {
        return new ServiceTerritoryMember(
            ServiceTerritoryId = serviceTerritoryId,
            ServiceResourceId = serviceResourceId,
            OperatingHoursId = operatingHoursId,
            EffectiveStartDate = System.now()
        );
    }


    public static List<Appointment_Resource__c> createTestAppointmentResources(Id serviceAppointmentId, Id resourceId, Integer numberOfResources) {
        List<Appointment_Resource__c> testResources = new List<Appointment_Resource__c>();
        for (Integer i = 0; i < numberOfResources; i++) {
            testResources.add(
                new Appointment_Resource__c(
                    Service_Appointment__c = serviceAppointmentId,
                    Resource__c = resourceId,
                    Fixed_Fee__c = 50.00,
                    Special_Tariffication_Fee__c = 25.00,
                    Bonus__c = 10.00,
                    Contractor_Comment__c = 'Test Comment',
                    Description__c = 'Test Description'
                )
            );
        }
        return testResources;
    }

    public static Capacity__c createTestCapacity(String workTypeName,String region) {
        return new Capacity__c(
            Work_Type__c = workTypeName,
            Region__c = region,
            Week_Start__c = Date.today().toStartOfWeek(),
            Week_End__c = Date.today().toStartOfWeek().addDays(6),
            Year__c	= '2024',
            Week__c = 34,
            Contract_Type__c = '112',
            Capacity_Remaining__c = 10
        );
    }

    public static Ouverture_Fermeture_work_types__c createTestCapacityCustomSettings(String name,Integer priority) {
        return new Ouverture_Fermeture_work_types__c(
            Name = name, 
            Name__c = name,
            Product_Conditions__c = '12345 OR 54321 AND ( 32844 OR 328488)',
            Priority__c = priority
        );
    }




    public static Map<String, Object> createRegistrationData() {
        return new Map<String, Object>{
            // Account fields
            'accountName' => 'Test Account',
            'accountDescription' => 'This is a test account created for registration',
            'accountType' => 'Residential',
            'accountLanguage' => 'F',
            'accountSource' => 'Website',
            
            // Billing address
            'billingStreet' => '123 Billing Street',
            'billingCity' => 'Billing City',
            'billingState' => 'ON',
            'billingPostalCode' => '000 000',
            'billingCountry' => 'CA',
            
            // Shipping address
            'shippingStreet' => '456 Shipping Street',
            'shippingCity' => 'Shipping City',
            'shippingState' => 'QC',
            'shippingPostalCode' => '000 000',
            'shippingCountry' => 'CA',
            
            // Contact fields
            'firstName' => 'Test',
            'lastName' => 'User',
            'birthDate' => Date.today().addYears(-30).format(),
            'email' => 'test.user' + Datetime.now().getTime() + '@example.com',
            'mobilePhone' => '5141234567',
            'homePhone' => '5149876543',
            'doNotCall' => false,
            'emailOptOut' => false
        };
    }

    public static Map<String, Object> createFormData() {
        return new Map<String, Object>{
            'isAddressCorrect' => true,
            'addressComment' => 'Confirmed correct address',
            'isContractCorrect' => true,
            'remplacementSelection' => false,
            'meubleSelection' => true,
            'terrainDroitSelection' => true,
            'hlAccessSelection' => false,
            'demonteeSelection' => true,
            'installationSelection' => true,
            'gazonSelection' => true,
            'hlObstacle' => false,
            'contractComment' => 'All terms accepted',
            'hlGradeurComment' => 'Standard height clearance',
            'deniveleComment' => 'Level terrain',
            'spaAreaComment' => 'Perfect location identified',
            'deliveryLocation' => 'Front driveway',
            'spaAreaLocation' => 'Backyard patio area',
            'meubleComment' => 'No furniture to move',
            'endroitInstallation' => 'Deck area',
            'comminicationPreference' => 'phone',
            'accessMeetsRequirements' => true,
            'wantToBeContacted' => false,
            'phoneNumber' => '514-555-9876',
            'acComment' => 'Air conditioning unit nearby',
            'abComment' => 'Above ground installation preferred'
        };
    }

    public static Postal_Code__c createPostalCode(String name) {
        return new Postal_Code__c(
            Name = name
        );
    }


    public static void createServiceAppointmentTestData() {
        // Create Settings
        Contractor_Invoice_Settings__c settings = createServiceAppointmentSettings();
        insert settings;

        User testUser = createTestUser('test','lmeo',null);
        insert testUser;
    
        // Create Product
        Product2 testProduct = createTestProduct('Test Product','TEST-PROD-001');
        insert testProduct;

        // Create Standard Pricebook Entry
        PricebookEntry standardPricebookEntry = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = testProduct.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert standardPricebookEntry;

        // Create Test Pricebook
        Pricebook2 testPricebook = createTestPricebook();
        insert testPricebook;

        // Create Test Pricebook Entry
        PricebookEntry testPricebookEntry = new PricebookEntry(
            Pricebook2Id = testPricebook.Id,
            Product2Id = testProduct.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert testPricebookEntry;

        Account testAccount = createTestAccount();
        insert testAccount;
        System.debug('testAccount ' + testAccount.Id);

        // Create Resource

        // Create Work Type
        WorkType workType = createTestWorkType(testProduct.Id);
        insert workType;

        // Create Work Order
        WorkOrder workOrder = createTestWorkOrder(testAccount.Id);
        insert workOrder;

        // Create Work Order Line Item
        WorkOrderLineItem woli = createTestWorkOrderLineItem(workOrder.Id, null, workType.Id, testProduct.Id);
        insert woli;
        System.debug('woli ' + woli);

        Resource__c testResource = createTestResource(testPricebook.Id,testAccount.Id);
        insert testResource;
        System.debug('testResource ' + testResource);

        OperatingHours testOperatingHours = createTestOperatingHours();
        insert testOperatingHours;
        System.debug('testOperatingHours ' + testOperatingHours);

        ServiceTerritory testServiceTerritory = createTestServiceTerritory(testOperatingHours.Id);
        insert testServiceTerritory;
        System.debug('testServiceTerritory ' + testServiceTerritory);

        ServiceResource testServiceResource = createTestServiceResource(testAccount.Id,testUser.Id);
        insert testServiceResource;
        System.debug('testServiceResource ' + testServiceResource);
        // Create Service Appointment
        ServiceAppointment testServiceAppointment = createTestServiceAppointment(woli.Id,testServiceTerritory.Id,testServiceResource.Id);
        insert testServiceAppointment;

        ServiceTerritoryMember testServiceTerritoryMember = createTestServiceTerritoryMember(testServiceTerritory.Id,testServiceResource.Id,testOperatingHours.Id);
        insert testServiceTerritoryMember;
         
 
        AssignedResource testAssignedResource = createTestAssignedResource(testServiceResource.Id,testServiceAppointment.Id);
 
        insert testAssignedResource;

        // Create Appointment Resources
        List<Appointment_Resource__c> testResources = createTestAppointmentResources(
            testServiceAppointment.Id, 
            testResource.Id, 
            1
        );
        
        insert testResources;

    }

    // Method to create a complete test data set
    public static void createCompleteTestData() {
        Id standardPricebookId = Test.getStandardPricebookId();
        
        Account testAccount = createTestAccount();
        insert testAccount;
        
        Contact testContact = createTestContact(testAccount.Id);
        insert testContact;

        Product2 testProduct = createTestProduct('Test Product','TEST-PROD-001');
        insert testProduct;
        
        Product2 testProduct2 = createTestProduct('Test Produc 2','TEST-PROD-002');
        insert testProduct2;

        PricebookEntry standardPricebookEntry = createTestPricebookEntry(testProduct.Id, standardPricebookId);
        insert standardPricebookEntry;
        
        Order testOrder = createTestOrder(testAccount.Id, standardPricebookId,'CONTRACT-001');
        insert testOrder;
        
        OrderItem testOrderItem = createTestOrderItem(testOrder.Id, testProduct.Id, standardPricebookEntry.Id);
        insert testOrderItem;

        OrderItem testOrderItem2 = createTestOrderItem(testOrder.Id, testProduct.Id, standardPricebookEntry.Id);
        insert testOrderItem2;

        OrderItem testOrderItem3 = createTestOrderItem(testOrder.Id, testProduct2.Id, standardPricebookEntry.Id);
        insert testOrderItem3;


        WorkType workType = createTestWorkType(testProduct.Id);
        insert workType;

        // Create Work Order
        WorkOrder workOrder = createTestWorkOrder(testAccount.Id);
        insert workOrder;

        WorkOrderLineItem woli = createTestWorkOrderLineItem(workOrder.Id, testOrder.Id, workType.Id, testProduct.Id);
        insert woli;

        Shipment testShipment = createTestShipment(testOrder.Id);
        insert testShipment;
        
        ShipmentItem testShipmentItem = createTestShipmentItems(testShipment.Id,testProduct.Id);
        insert testShipmentItem;

        Order testOrder1 = createTestOrder(testAccount.Id, standardPricebookId,'CONTRACT-001');
        insert testOrder1;

        Order testOrder2 = createTestOrder(testAccount.Id, standardPricebookId,'CONTRACT-00-2');
        insert testOrder2;

        User testUser = createTestUser('test','lmeo',null);
        insert testUser;

        Resource__c testResource = createTestResource(standardPricebookId,testAccount.Id);
        insert testResource;
        System.debug('testResource ' + testResource);

        OperatingHours testOperatingHours = createTestOperatingHours();
        insert testOperatingHours;
        System.debug('testOperatingHours ' + testOperatingHours);

        ServiceTerritory testServiceTerritory = createTestServiceTerritory(testOperatingHours.Id);
        insert testServiceTerritory;
        System.debug('testServiceTerritory ' + testServiceTerritory);

        ServiceResource testServiceResource = createTestServiceResource(testAccount.Id,testUser.Id);
        insert testServiceResource;
        System.debug('testServiceResource ' + testServiceResource);
        // Create Service Appointment
        ServiceAppointment testServiceAppointment = createTestServiceAppointment(woli.Id,testServiceTerritory.Id,testServiceResource.Id);
        insert testServiceAppointment;


        
     }



     public static void createDataForCapacities() {
 

        Product2 testProduct = createTestProduct('Test Product','TEST-PROD-001');
        insert testProduct;
  
        WorkType workType = createTestWorkType(testProduct.Id);
        insert workType;
       
        Capacity__c capacity1 = createTestCapacity('Ouverture CR','Montreal');
        insert capacity1;
 
        Capacity__c capacity2 = createTestCapacity('Fermeture Spa','Quebec');
        insert capacity2;
 
        Capacity__c capacity3 = createTestCapacity('Fermeture HT','Gatineau/Ontario');
        insert capacity3;
 
        Ouverture_Fermeture_work_types__c customSetting1 = createTestCapacityCustomSettings('Livraison AB',1);
        insert customSetting1;
 
        Ouverture_Fermeture_work_types__c customSetting2 = createTestCapacityCustomSettings('Complex Work Type',2);
        insert customSetting2;
 
        Ouverture_Fermeture_work_types__c customSetting3 = createTestCapacityCustomSettings('Alternative Work Type',3);
        insert customSetting3;
 
        
     }





}